server:
  port: 8082
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC&&allowPublicKeyRetrieval=true
    username: root
    password: Acai123456
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    time-zone: GMT+8

mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包

logging:
  config: classpath:logConfig/logback-test.xml
